modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="not_enough_gamerules"
version="1.16.5-r1.1.1"
displayName="Not Enough Gamerules"
credits="Credits are on mod's page."
authors="Max094_Reikeb"
description='''
Not Enough Gamerules is a very simple mod that adds Gamerules.
'''

[[dependencies.not_enough_gamerules]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.not_enough_gamerules]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
