modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="not_enough_gamerules"
version="1.18.1-r1.4"
displayName="Not Enough Gamerules"
credits="Credits are on mod's page."
authors="Max094_Reikeb"
description='''
Not Enough Gamerules is a very simple mod that adds Gamerules.
'''

[[dependencies.not_enough_gamerules]] #optional
    modId="forge"
    mandatory=true
    versionRange="[39.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.not_enough_gamerules]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
