modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"

[[mods]]
modId="not_enough_gamerules"
version="1.19.3-r1.5.2"
displayName="Not Enough Gamerules"
credits="Credits are on mod's page."
authors="Max094_Reikeb"
description='''
Not Enough Gamerules is a very simple mod that adds Gamerules.
'''

[[dependencies.not_enough_gamerules]] #optional
    modId="forge"
    mandatory=true
    versionRange="[44.1.16,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.not_enough_gamerules]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
