modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="not_enough_gamerules"
version="1.19.2-r1.5.1"
displayName="Not Enough Gamerules"
credits="Credits are on mod's page."
authors="Max094_Reikeb"
description='''
Not Enough Gamerules is a very simple mod that adds Gamerules.
'''

[[dependencies.not_enough_gamerules]] #optional
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.not_enough_gamerules]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
